In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Student.csv")

In [3]:
df.head()

,Gender,Age,Academic Pressure,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,Male,28,2.0,4.0,7-8 hours,Moderate,Yes,9,2,Yes,No
1,Male,28,4.0,5.0,5-6 hours,Healthy,Yes,7,1,Yes,No
2,Male,25,1.0,3.0,5-6 hours,Unhealthy,Yes,10,4,No,Yes
3,Male,23,1.0,4.0,More than 8 hours,Unhealthy,Yes,7,2,Yes,No
4,Female,31,1.0,5.0,More than 8 hours,Healthy,Yes,4,2,Yes,No

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 502 entries, 0 to 501
Data columns (total 11 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Gender                                 502 non-null    object
 1   Age                                    502 non-null    int64
 2   Academic Pressure                      502 non-null    float64
 3   Study Satisfaction                     502 non-null    float64
 4   Sleep Duration                         502 non-null    object
 5   Dietary Habits                         502 non-null    object
 6   Have you ever had suicidal thoughts ?  502 non-null    object
 7   Study Hours                            502 non-null    int64
 8   Financial Stress                       502 non-null    int64
 9   Family History of Mental Illness       502 non-null    object
 10  Depression                             502 non-null    object
dtypes: float64(2), int64(3), object(6)
memory usage: 43.3+ KB

In [6]:
df.describe()

,Age,Academic Pressure,Study Satisfaction,Study Hours,Financial Stress
count,502.000000,502.000000,502.000000,502.000000,502.000000
mean,26.241036,3.003984,3.075697,6.404382,2.928287
std,4.896501,1.390007,1.373490,3.742434,1.425053
min,18.000000,1.000000,1.000000,0.000000,1.000000
25%,22.000000,2.000000,2.000000,3.000000,2.000000
50%,26.500000,3.000000,3.000000,7.000000,3.000000
75%,30.000000,4.000000,4.000000,10.000000,4.000000
max,34.000000,5.000000,5.000000,12.000000,5.000000

In [4]:
df.isnull().sum()

Gender                                   0
Age                                      0
Academic Pressure                        0
Study Satisfaction                       0
Sleep Duration                           0
Dietary Habits                           0
Have you ever had suicidal thoughts ?    0
Study Hours                              0
Financial Stress                         0
Family History of Mental Illness         0
Depression                               0
dtype: int64

In [7]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [17]:
df['Dietary Habits'].unique()

array(['Moderate', 'Healthy', 'Unhealthy'], dtype=object)

In [8]:
df['Sleep Duration'].unique()

array(['7-8 hours', '5-6 hours', 'More than 8 hours', 'Less than 5 hours'],
      dtype=object)

#Replacing categorical to numerical following columns
Gender,Sleep Duration,Dietary Habits and Have you ever had suicidal thoughts ?

In [9]:
df['Gender']=df['Gender'].replace({"Male":0,"Female":1})

/tmp/ipykernel_1656/54505873.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender']=df['Gender'].replace({"Male":0,"Female":1})

In [12]:
df['Sleep Duration']=df['Sleep Duration'].replace({"More than 8 hours":0,"7-8 hours":1,"5-6 hours":2,"Less than 5 hours":3})

/tmp/ipykernel_1656/1375515319.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Sleep Duration']=df['Sleep Duration'].replace({"More than 8 hours":0,"7-8 hours":1,"5-6 hours":2,"Less than 5 hours":3})

In [13]:
df['Have you ever had suicidal thoughts ?']=df['Have you ever had suicidal thoughts ?'].replace({"Yes":0,"No":1})

/tmp/ipykernel_1656/1077360063.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Have you ever had suicidal thoughts ?']=df['Have you ever had suicidal thoughts ?'].replace({"Yes":0,"No":1})

In [15]:
df['Family History of Mental Illness']=df['Family History of Mental Illness'].replace({"Yes":0,"No":1})

/tmp/ipykernel_1656/3283998893.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Family History of Mental Illness']=df['Family History of Mental Illness'].replace({"Yes":0,"No":1})

In [19]:
df['Dietary Habits']=df['Dietary Habits'].replace({"Moderate":0,"Healthy":1,"Unhealthy":2})

/tmp/ipykernel_1656/4241336523.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Dietary Habits']=df['Dietary Habits'].replace({"Moderate":0,"Healthy":1,"Unhealthy":2})

In [20]:
df.head()

,Gender,Age,Academic Pressure,Study Satisfaction,Sleep Duration,Dietary Habits,Have you ever had suicidal thoughts ?,Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,0,28,2.0,4.0,1,0,0,9,2,0,No
1,0,28,4.0,5.0,2,1,0,7,1,0,No
2,0,25,1.0,3.0,2,2,0,10,4,1,Yes
3,0,23,1.0,4.0,0,2,0,7,2,0,No
4,1,31,1.0,5.0,0,1,0,4,2,0,No

In [21]:
df.to_csv("Student.csv")